<?php

namespace Database\Seeders;

use App\Models\WardDetails;
use Illuminate\Database\Seeder;

class WardDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        WardDetails::create(['fldWardName' => 'Select Ward', 'fldIdCouncil' => '0']);

        WardDetails::create(['fldWardName' => 'Eluwapitiya', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Veyangoda', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Udammita Thalgasmote', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Nittambuwa', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Parana Veyangoda', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Dadagamuwa', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Magalegoda', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Bemmulla', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Raniswala', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Katuwasgoda', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Thihariya', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Kaththota', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Ellakkala', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Attanagalla', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Palkumbura', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Alawala', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Urapola', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Mathalana', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Ogodapola', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Bonegala', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Koskandawala', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Paranagama', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Walgammulla', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Bopagama', 'fldIdCouncil' => '1']);
        WardDetails::create(['fldWardName' => 'Pahala Biyanvila', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Ihala Biyanvila North', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Ihala Biyanvila Central', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Mawaramandiya', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Makola Notrh Ihala', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Pahala Biyanvila West', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Makola North Pahala', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Makola North Central', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Makola South Ihala', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Heiyanthuduwa North', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Siyambalape North', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Meegahawatta', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Siyambalapewaththa', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Delgoda', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Kanduboda', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Yatihena', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Siyambalape South', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Heiyanthuduwa East', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Sapugaskanda', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Gonawala East', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Pamunuvila', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Gonawala West', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Gonawala Central', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Bollegala', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Pattivila', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Mabima', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Heiyanthuduwa', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Biyagama South West', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Biyagama North East', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Yabaraluwa', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Malwana', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Walgama East', 'fldIdCouncil' => '2']);
        WardDetails::create(['fldWardName' => 'Badalgama', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Mellawagedara', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Kotadeniyawa', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Nawana', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Halpe', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Kithulwala', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Maditiyawala', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Walpita', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Delwagura', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Godigamuwa', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Akaragama', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Pahala Madampella', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Kongodamulla West', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Kadawala', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Induragara', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Palliyapitiya', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Barawawila', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Balagalla', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Divulapitiya', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Bomugammana', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Henpitagedara', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Dunagaha', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Dagonna', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Aluthapola', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Assennawaththa', 'fldIdCouncil' => '3']);
        WardDetails::create(['fldWardName' => 'Wathurugama', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Diyawala', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Millathe', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Udagama', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Meethirigala', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Kirindiwela', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Radawana', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Nedungolla', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Pepiliyawala', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Ganihigama', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Dangalla', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Pugoda', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Pelpita', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Mandawala', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Keragala', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Demalagama', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Kalukondayawa', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Dekatana', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Pelahela', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Lunugama', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Giridara', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Samanabedda', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Iddamaldeniya', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Dompe', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Mapitigama', 'fldIdCouncil' => '4']);
        WardDetails::create(['fldWardName' => 'Thittalapitigoda', 'fldIdCouncil' => '5']);
        WardDetails::create(['fldWardName' => 'Aluthgama Bogamuwa North', 'fldIdCouncil' => '5']);
        WardDetails::create(['fldWardName' => 'Aluthgama Bogamuwa South', 'fldIdCouncil' => '5']);
        WardDetails::create(['fldWardName' => 'Weediyawatta', 'fldIdCouncil' => '5']);
        WardDetails::create(['fldWardName' => 'Keselwathugoda', 'fldIdCouncil' => '5']);
        WardDetails::create(['fldWardName' => 'Indigolla', 'fldIdCouncil' => '5']);
        WardDetails::create(['fldWardName' => 'Ihalagama East', 'fldIdCouncil' => '5']);
        WardDetails::create(['fldWardName' => 'Ihalagama West', 'fldIdCouncil' => '5']);
        WardDetails::create(['fldWardName' => 'Medagama', 'fldIdCouncil' => '5']);
        WardDetails::create(['fldWardName' => 'Pahalagama', 'fldIdCouncil' => '5']);
        WardDetails::create(['fldWardName' => 'Bandiyamulla', 'fldIdCouncil' => '5']);
        WardDetails::create(['fldWardName' => 'Kidagammulla', 'fldIdCouncil' => '5']);
        WardDetails::create(['fldWardName' => 'Gampaha Aluthgama East', 'fldIdCouncil' => '5']);
        WardDetails::create(['fldWardName' => 'Yakkala North', 'fldIdCouncil' => '5']);
        WardDetails::create(['fldWardName' => 'Yakkala West', 'fldIdCouncil' => '5']);
        WardDetails::create(['fldWardName' => 'Yakkala', 'fldIdCouncil' => '5']);
        WardDetails::create(['fldWardName' => 'Henarathgoda', 'fldIdCouncil' => '5']);
        WardDetails::create(['fldWardName' => 'Makevita', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Akaravita', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Thibbotugoda', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Bulugahagoda', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Bollatha', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Galahitiyawa', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Ganemulla', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Pahala Yagoda', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Orutota', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Mudungoda', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Rathupaswala', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Belummahara', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Ihala Yagoda', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Kossinna', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Katuwalamulla', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Parakandeniya', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Amunugoda', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Pahala Imbulgoda', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Ihala Imbulgoda', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Nedungamuwa', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Weliweriya', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Embaraluwa', 'fldIdCouncil' => '6']);
        WardDetails::create(['fldWardName' => 'Thudella', 'fldIdCouncil' => '7']);
        WardDetails::create(['fldWardName' => 'Kanuwana', 'fldIdCouncil' => '7']);
        WardDetails::create(['fldWardName' => 'Ja-Ela', 'fldIdCouncil' => '7']);
        WardDetails::create(['fldWardName' => 'Weligampitiya North', 'fldIdCouncil' => '7']);
        WardDetails::create(['fldWardName' => 'Indivitiya', 'fldIdCouncil' => '7']);
        WardDetails::create(['fldWardName' => 'Weligampitiya South', 'fldIdCouncil' => '7']);
        WardDetails::create(['fldWardName' => 'Kapuwatta', 'fldIdCouncil' => '7']);
        WardDetails::create(['fldWardName' => 'Wewala', 'fldIdCouncil' => '7']);
        WardDetails::create(['fldWardName' => 'Kalaeliya', 'fldIdCouncil' => '7']);
        WardDetails::create(['fldWardName' => 'Dandugama', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Kudahakapola South', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Gallawatta', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Mahawatta', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Ekala', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Niwandama', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Bandigoda', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Alexendrawatta', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Maeliya', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Indiminna', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Dolahena', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Polpithimukalana', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Batuwatta', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Narangodapaluwa', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Walpola', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Jayasirigama', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Hapugoda', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Rilaulla', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Kandana', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Nagoda', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Jayasamarugama', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Peralanda', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Ragama', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Podiweekumbura', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Ketagewatta', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Dambuwa', 'fldIdCouncil' => '8']);
        WardDetails::create(['fldWardName' => 'Thoppuwa', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Katana', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Ethgala', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Kandawala', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Welihena', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Silvapura', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Kondagammulla', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Kadirana North', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Thimbirigaskatuwa', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Katuwapitiya', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Kadirana', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Akkarapanaha', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Kimbulapitiya Central', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Kimbulapitiya West', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Andiambalama', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Dewamottawa', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Madawala', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Heenatiyana', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Kuswala', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Raddoluwagama', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Raddoluwa North', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Raddoluwa', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Kotugoda', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Udammita', 'fldIdCouncil' => '9']);
        WardDetails::create(['fldWardName' => 'Kurana-Katunayake', 'fldIdCouncil' => '10']);
        WardDetails::create(['fldWardName' => 'Kurana Central', 'fldIdCouncil' => '10']);
        WardDetails::create(['fldWardName' => 'Katunayake', 'fldIdCouncil' => '10']);
        WardDetails::create(['fldWardName' => 'Liyanagemulla North', 'fldIdCouncil' => '10']);
        WardDetails::create(['fldWardName' => 'Amandoluwa', 'fldIdCouncil' => '10']);
        WardDetails::create(['fldWardName' => 'Liyanagemulla South', 'fldIdCouncil' => '10']);
        WardDetails::create(['fldWardName' => 'Mookalangamuwa', 'fldIdCouncil' => '10']);
        WardDetails::create(['fldWardName' => 'Seeduwa', 'fldIdCouncil' => '10']);
        WardDetails::create(['fldWardName' => 'Mookalangamuwa East', 'fldIdCouncil' => '10']);
        WardDetails::create(['fldWardName' => 'Bandarawatta', 'fldIdCouncil' => '10']);
        WardDetails::create(['fldWardName' => 'Ambalanmulla', 'fldIdCouncil' => '10']);
        WardDetails::create(['fldWardName' => 'Hunupitiya North', 'fldIdCouncil' => '11']);
        WardDetails::create(['fldWardName' => 'Nahena', 'fldIdCouncil' => '11']);
    }
}
